spring.application.name=performancepulse-backend

server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:performance_pulse}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:M.sujitha@2006}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (In production this should be a strong random key from environment variables)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b8db0425c6a1e4b105dbe0c52bb881d7
jwt.expirationMs=86400000
